### ISSUE TITLE
Reference against stable Avalonia packages

### ISSUE THREAD

**Issue by MarcusWichelmann** [wieslawsoltes/ThemeEditor#10]
This project is always using the latest Avalonia CI builds, which results in builds failing with `Detected package downgrade` errors as soon as Avalonia uses a more up to date version of e.g. `SkiaSharp.NativeAssets.Linux` than this project does:

```
error NU1605: Detected package downgrade: SkiaSharp.NativeAssets.Linux from 1.68.2 to 1.68.1. Reference the package directly from the project to select a different version.
error NU1605:  ThemeEditor -> Avalonia.Desktop 0.9.999-cibuild0007071-beta -> Avalonia.Skia 0.9.999-cibuild0007071-beta -> SkiaSharp.NativeAssets.Linux (>= 1.68.2)
error NU1605:  ThemeEditor -> SkiaSharp.NativeAssets.Linux (>= 1.68.1)
```

Could you please consider referencing against stable Avalonia builds to prevent this great tool from breaking over time?

**Comment by wieslawsoltes** [comment]
Master branch follows master branch of Avalonia

**Comment by wieslawsoltes** [comment]
Please use `release/*` branches for stable Avalonia, e.g. https://github.com/wieslawsoltes/ThemeEditor/tree/release/0.9.4

**Comment by MarcusWichelmann** [comment]
@wieslawsoltes Aah, that makes sense, didn't taks any notice of these branches. Maybe add a hint to that to the readme?
