### ISSUE TITLE
ColorPicker doesnt show / blank

### ISSUE THREAD

**Issue by sn4k3** [wieslawsoltes/ThemeEditor#12]
I'm trying to use the ColorPicker but when declared nothing shows.
I'm not sure if it require more code to make it work but i'm calling the control like any other:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:cp="clr-namespace:ThemeEditor.Controls.ColorPicker;assembly=ThemeEditor.Controls.ColorPicker"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="UVtools.WPF.Windows.ColorPickerWindow"
        Title="ColorPickerWindow">
  <cp:ColorPicker/>
</Window>
```
Using last preview version of both colorpicker + avalonia

**Comment by wieslawsoltes** [comment]
https://github.com/wieslawsoltes/ThemeEditor/blob/15053515d97fe33e7708b37b3862a3aff6f46151/src/ThemeEditor/App.xaml#L23

**Comment by sn4k3** [comment]
That did the trick. 
I'm new to avalonia and WPF still learning...
Thanks for pointing out
